### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by fitz-vivodyne** [honeycombio/gha-buildevents#288]
**Is your feature request related to a problem? Please describe.**

I'm trying gha-buildevents for the first time and followed the example in the README, which includes this block for a multi-job workflow:
```yaml
    - name: Set trace-start
      id: set-trace-start
      run: |
        echo ::set-output name=trace-start::$(date +%s)
```
I noticed the following warning in the logs:
`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Describe the solution you'd like**

Update the README to write to `$GITHUB_OUTPUT` instead, assuming it looks something like this:
```yaml
    - name: Set trace-start
      id: set-trace-start
      run: |
        echo trace-start=$(date +%s) >> $GITHUB_OUTPUT
```

**Describe alternatives you've considered**

**Additional context**
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
