### ISSUE TITLE
Make gha-buildevents-step to simplify working with steps

### ISSUE THREAD

**Issue by kvrhdn** [honeycombio/gha-buildevents#5]
Proposal:

```yaml
  # install buildevents, captures the start of the build
  # sets env variables: BUILD_ID, STEP_ID, STEP_START
- uses: kvrhdn/gha-buildevents@master
  with:
    apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
    dataset: my-dataset
    job-status: ${{ job.status }}
  
... do some work here...

  # this will simply call 'buildevents step' for you
- uses: kvrhdn/gha-buildevents-step@master
  with:
    name: initialize

... do some more work here, i.e. build the app...

- uses: kvrhdn/gha-buildevents-step@master
  with:
    name: build-app

... and do some more work here, i.e. deploy the app...

- uses: kvrhdn/gha-buildevents-step@master
  with:
    name: deploy-app

  # end of workflow, gha-buildevents automatically wraps up and builds the trace
```
